### ISSUE TITLE
Upgrade disgord version

### ISSUE THREAD

**Issue by andersfylling** [NyanKiyoshi/disgord-plugin-router#3]
Hi, just notifying that Discord decided to do a breaking change to their API that takes place within less than a month. Because of this I suggest upgrading to v0.11 (the latest release) such that your application does not cease to function. Sorry about the inconvenience!

Source: https://github.com/discordapp/discord-api-docs/pull/967

**Comment by andersfylling** [comment]
I see you are using v0.9, so I highly recommend reading the docs/CHANGELOG-v0.10 as _many_ functions have been renamed to provide a more consistent interface.

**Comment by NyanKiyoshi** [comment]
Hi! Thanks a lot for the information! I have very limited available time, but hopefully I can do that ASAP.

**Comment by NyanKiyoshi** [comment]
Archiving as I don't have the time to maintain and as you told me some long time ago you were planning on making this a feature 👍
